# Generated by Django 3.1.5 on 2021-01-16 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('api_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('double_damage_to', models.ManyToManyField(related_name='_type_double_damage_to_+', to='pokemon.Type')),
                ('half_damage_from', models.ManyToManyField(related_name='_type_half_damage_from_+', to='pokemon.Type')),
                ('half_damage_to', models.ManyToManyField(related_name='_type_half_damage_to_+', to='pokemon.Type')),
                ('no_damage_to', models.ManyToManyField(related_name='_type_no_damage_to_+', to='pokemon.Type')),
            ],
        ),
        migrations.CreateModel(
            name='PokemonStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('stats', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.stat')),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('id_pokedex', models.IntegerField()),
                ('stats', models.ManyToManyField(to='pokemon.PokemonStats')),
                ('types', models.ManyToManyField(to='pokemon.Type')),
            ],
        ),
        migrations.CreateModel(
            name='Evolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('evolution_method', models.CharField(max_length=100)),
                ('evolution_object', models.CharField(max_length=100)),
                ('evolution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evolutions', to='pokemon.pokemon')),
                ('preevolution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preevolutions', to='pokemon.pokemon')),
            ],
        ),
    ]
