# Generated by Django 3.1.5 on 2021-01-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_auto_20210115_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stat',
            name='api_id',
        ),
        migrations.AlterField(
            model_name='type',
            name='api_id',
            field=models.IntegerField(null=True),
        ),
    ]
