# Generated by Django 3.1.5 on 2021-01-16 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0004_auto_20210116_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evolution',
            name='level',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pokemonstats',
            name='pokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='pokemon.pokemon'),
        ),
    ]
